# Generated by Django 3.1.5 on 2021-01-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210125_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Producer',
            new_name='producer',
        ),
    ]
